### ISSUE TITLE
lost main index layout

### ISSUE THREAD

**Issue by stpriyanka** [devbridge/BetterCMS.Demo#20]
When I tried to change my page layout with a template later on I could not able to recover it. did i lost my previous layout after put another template ? Is there any way to recover your last working layout ?

**Comment by smikulenas** [comment]
If you are asking functionality like undo - no, we do not have page history. If you changed current page layout and now page somehow do not render even cms controls, try to go to different cms page (that renders correctly), than navigate to failing page settings via cms side menu (Site Settings -> Pages) and change the layout.
